#ifndef FRT_INTERNAL_H
#define FRT_INTERNAL_H

/* Functions */
#define filt_eq                                        frt_filt_eq
#define filt_get_bv                                    frt_filt_get_bv
#define filt_hash                                      frt_filt_hash
#define filter_clone_size                              frt_filter_clone_size
#define filter_ft                                      frt_filter_ft
#define fis_add_field                                  frt_fis_add_field
#define fis_by_number                                  frt_fis_by_number
#define fis_deref                                      frt_fis_deref
#define fis_get_field                                  frt_fis_get_field
#define fis_get_field_num                              frt_fis_get_field_num
#define fis_get_or_add_field                           frt_fis_get_or_add_field
#define fis_new                                        frt_fis_new
#define fis_read                                       frt_fis_read
#define fis_to_s                                       frt_fis_to_s
#define fis_write                                      frt_fis_write
#define float2byte                                     frt_float2byte
#define float2int                                      frt_float2int
#define fn_for_generation                              frt_fn_for_generation
#define fq_new                                         frt_fq_new
#define fr_clone                                       frt_fr_clone
#define fr_close                                       frt_fr_close
#define fr_get_doc                                     frt_fr_get_doc
#define fr_get_field_tv                                frt_fr_get_field_tv
#define fr_get_lazy_doc                                frt_fr_get_lazy_doc
#define fr_get_tv                                      frt_fr_get_tv
#define fr_open                                        frt_fr_open
#define free_ft                                        frt_free_ft
#define fshq_pq_destroy                                frt_fshq_pq_destroy
#define fshq_pq_down                                   frt_fshq_pq_down
#define fshq_pq_insert                                 frt_fshq_pq_insert
#define fshq_pq_new                                    frt_fshq_pq_new
#define fshq_pq_pop                                    frt_fshq_pq_pop
#define fshq_pq_pop_fd                                 frt_fshq_pq_pop_fd
#define fuzq_new                                       frt_fuzq_new
#define fuzq_new_conf                                  frt_fuzq_new_conf
#define fuzq_score                                     frt_fuzq_score
#define fw_add_doc                                     frt_fw_add_doc
#define fw_add_postings                                frt_fw_add_postings
#define fw_close                                       frt_fw_close
#define fw_open                                        frt_fw_open
#define fw_write_tv_index                              frt_fw_write_tv_index
#define get_float_value                                frt_get_float_value
#define get_integer_value                              frt_get_integer_value
#define get_stacktrace                                 frt_get_stacktrace
#define get_string_value                               frt_get_string_value
#define h_clear                                        frt_h_clear
#define h_clone                                        frt_h_clone
#define h_clone_ft                                     frt_h_clone_ft
#define h_del                                          frt_h_del
#define h_del_int                                      frt_h_del_int
#define h_destroy                                      frt_h_destroy
#define h_each                                         frt_h_each
#define h_each_key_val_ft                              frt_h_each_key_val_ft
#define h_get                                          frt_h_get
#define h_get_int                                      frt_h_get_int
#define h_has_key                                      frt_h_has_key
#define h_has_key_int                                  frt_h_has_key_int
#define h_lookup                                       frt_h_lookup
#define h_lookup_ft                                    frt_h_lookup_ft
#define h_new                                          frt_h_new
#define h_new_int                                      frt_h_new_int
#define h_new_ptr                                      frt_h_new_ptr
#define h_new_str                                      frt_h_new_str
#define h_rem                                          frt_h_rem
#define h_rem_int                                      frt_h_rem_int
#define h_set                                          frt_h_set
#define h_set_ext                                      frt_h_set_ext
#define h_set_int                                      frt_h_set_int
#define h_set_safe                                     frt_h_set_safe
#define h_set_safe_int                                 frt_h_set_safe_int
#define h_str_print_keys                               frt_h_str_print_keys
#define hash_finalize                                  frt_hash_finalize
#define hash_ft                                        frt_hash_ft
#define hlp_string_diff                                frt_hlp_string_diff
#define hs_add                                         frt_hs_add
#define hs_add_safe                                    frt_hs_add_safe
#define hs_clear                                       frt_hs_clear
#define hs_del                                         frt_hs_del
#define hs_destroy                                     frt_hs_destroy
#define hs_exists                                      frt_hs_exists
#define hs_free                                        frt_hs_free
#define hs_merge                                       frt_hs_merge
#define hs_new                                         frt_hs_new
#define hs_new_ptr                                     frt_hs_new_ptr
#define hs_new_str                                     frt_hs_new_str
#define hs_orig                                        frt_hs_orig
#define hs_rem                                         frt_hs_rem
#define hyphen_filter_new                              frt_hyphen_filter_new
#define i16                                            frt_i16
#define i32                                            frt_i32
#define i64                                            frt_i64
#define icmp                                           frt_icmp
#define icmp_risky                                     frt_icmp_risky
#define imalloc                                        frt_imalloc
#define index_add_array                                frt_index_add_array
#define index_add_doc                                  frt_index_add_doc
#define index_add_string                               frt_index_add_string
#define index_auto_flush_ir                            frt_index_auto_flush_ir
#define index_auto_flush_iw                            frt_index_auto_flush_iw
#define index_create                                   frt_index_create
#define index_delete                                   frt_index_delete
#define index_delete_id                                frt_index_delete_id
#define index_delete_query                             frt_index_delete_query
#define index_delete_query_str                         frt_index_delete_query_str
#define index_delete_term                              frt_index_delete_term
#define index_destroy                                  frt_index_destroy
#define index_explain                                  frt_index_explain
#define index_flush                                    frt_index_flush
#define index_get_doc                                  frt_index_get_doc
#define index_get_doc_id                               frt_index_get_doc_id
#define index_get_doc_term                             frt_index_get_doc_term
#define index_get_doc_ts                               frt_index_get_doc_ts
#define index_get_query                                frt_index_get_query
#define index_has_del                                  frt_index_has_del
#define index_is_deleted                               frt_index_is_deleted
#define index_is_locked                                frt_index_is_locked
#define index_new                                      frt_index_new
#define index_optimize                                 frt_index_optimize
#define index_search_str                               frt_index_search_str
#define index_size                                     frt_index_size
#define index_term_id                                  frt_index_term_id
#define init                                           frt_init
#define int2float                                      frt_int2float
#define ir_add_cache                                   frt_ir_add_cache
#define ir_close                                       frt_ir_close
#define ir_commit                                      frt_ir_commit
#define ir_create                                      frt_ir_create
#define ir_delete_doc                                  frt_ir_delete_doc
#define ir_destroy                                     frt_ir_destroy
#define ir_doc_freq                                    frt_ir_doc_freq
#define ir_get_doc_with_term                           frt_ir_get_doc_with_term
#define ir_get_field_num                               frt_ir_get_field_num
#define ir_get_norms                                   frt_ir_get_norms
#define ir_get_norms_i                                 frt_ir_get_norms_i
#define ir_get_norms_into                              frt_ir_get_norms_into
#define ir_index_exists                                frt_ir_index_exists
#define ir_is_latest                                   frt_ir_is_latest
#define ir_open                                        frt_ir_open
#define ir_set_norm                                    frt_ir_set_norm
#define ir_term_positions_for                          frt_ir_term_positions_for
#define ir_terms                                       frt_ir_terms
#define ir_terms_from                                  frt_ir_terms_from
#define ir_undelete_all                                frt_ir_undelete_all
#define is2os_copy_bytes                               frt_is2os_copy_bytes
#define is2os_copy_vints                               frt_is2os_copy_vints
#define is_clone                                       frt_is_clone
#define is_close                                       frt_is_close
#define is_new                                         frt_is_new
#define is_pos                                         frt_is_pos
#define is_read_byte                                   frt_is_read_byte
#define is_read_bytes                                  frt_is_read_bytes
#define is_read_i32                                    frt_is_read_i32
#define is_read_i64                                    frt_is_read_i64
#define is_read_string                                 frt_is_read_string
#define is_read_string_safe                            frt_is_read_string_safe
#define is_read_u32                                    frt_is_read_u32
#define is_read_u64                                    frt_is_read_u64
#define is_read_vint                                   frt_is_read_vint
#define is_read_vll                                    frt_is_read_vll
#define is_read_voff_t                                 frt_is_read_voff_t
#define is_seek                                        frt_is_seek
#define is_skip_vints                                  frt_is_skip_vints
#define isea_doc_freq                                  frt_isea_doc_freq
#define isea_new                                       frt_isea_new
#define iw_add_doc                                     frt_iw_add_doc
#define iw_add_readers                                 frt_iw_add_readers
#define iw_close                                       frt_iw_close
#define iw_commit                                      frt_iw_commit
#define iw_delete_term                                 frt_iw_delete_term
#define iw_delete_terms                                frt_iw_delete_terms
#define iw_doc_count                                   frt_iw_doc_count
#define iw_open                                        frt_iw_open
#define iw_optimize                                    frt_iw_optimize
#define lazy_df_get_bytes                              frt_lazy_df_get_bytes
#define lazy_df_get_data                               frt_lazy_df_get_data
#define lazy_doc_close                                 frt_lazy_doc_close
#define lazy_doc_get                                   frt_lazy_doc_get
#define legacy_standard_analyzer_new                   frt_legacy_standard_analyzer_new
#define legacy_standard_analyzer_new_with_words        frt_legacy_standard_analyzer_new_with_words
#define legacy_standard_analyzer_new_with_words_len    frt_legacy_standard_analyzer_new_with_words_len
#define legacy_standard_tokenizer_new                  frt_legacy_standard_tokenizer_new
#define letter_analyzer_new                            frt_letter_analyzer_new
#define letter_tokenizer_new                           frt_letter_tokenizer_new
#define lmalloc                                        frt_lmalloc
#define lowercase_filter_new                           frt_lowercase_filter_new
#define lt_ft                                          frt_lt_ft
#define mapping_filter_add                             frt_mapping_filter_add
#define mapping_filter_new                             frt_mapping_filter_new
#define maq_new                                        frt_maq_new
#define matchv_add                                     frt_matchv_add
#define matchv_compact                                 frt_matchv_compact
#define matchv_compact_with_breaks                     frt_matchv_compact_with_breaks
#define matchv_destroy                                 frt_matchv_destroy
#define matchv_new                                     frt_matchv_new
#define matchv_sort                                    frt_matchv_sort
#define mb_legacy_standard_analyzer_new                frt_mb_legacy_standard_analyzer_new
#define mb_legacy_standard_analyzer_new_with_words     frt_mb_legacy_standard_analyzer_new_with_words
#define mb_legacy_standard_analyzer_new_with_words_len frt_mb_legacy_standard_analyzer_new_with_words_len
#define mb_legacy_standard_tokenizer_new               frt_mb_legacy_standard_tokenizer_new
#define mb_letter_analyzer_new                         frt_mb_letter_analyzer_new
#define mb_letter_tokenizer_new                        frt_mb_letter_tokenizer_new
#define mb_lowercase_filter_new                        frt_mb_lowercase_filter_new
#define mb_standard_analyzer_new                       frt_mb_standard_analyzer_new
#define mb_standard_analyzer_new_with_words            frt_mb_standard_analyzer_new_with_words
#define mb_standard_analyzer_new_with_words_len        frt_mb_standard_analyzer_new_with_words_len
#define mb_standard_tokenizer_new                      frt_mb_standard_tokenizer_new
#define mb_whitespace_analyzer_new                     frt_mb_whitespace_analyzer_new
#define mb_whitespace_tokenizer_new                    frt_mb_whitespace_tokenizer_new
#define mp_alloc                                       frt_mp_alloc
#define mp_destroy                                     frt_mp_destroy
#define mp_memdup                                      frt_mp_memdup
#define mp_new                                         frt_mp_new
#define mp_new_capa                                    frt_mp_new_capa
#define mp_reset                                       frt_mp_reset
#define mp_strdup                                      frt_mp_strdup
#define mp_strndup                                     frt_mp_strndup
#define mp_used                                        frt_mp_used
#define mr_get_field_num                               frt_mr_get_field_num
#define mr_open                                        frt_mr_open
#define msea_new                                       frt_msea_new
#define mtdpe_new                                      frt_mtdpe_new
#define mte_new                                        frt_mte_new
#define mulmap_add_mapping                             frt_mulmap_add_mapping
#define mulmap_compile                                 frt_mulmap_compile
#define mulmap_destroy                                 frt_mulmap_destroy
#define mulmap_dynamic_map                             frt_mulmap_dynamic_map
#define mulmap_map                                     frt_mulmap_map
#define mulmap_map_len                                 frt_mulmap_map_len
#define mulmap_new                                     frt_mulmap_new
#define multi_tq_add_term                              frt_multi_tq_add_term
#define multi_tq_add_term_boost                        frt_multi_tq_add_term_boost
#define multi_tq_new                                   frt_multi_tq_new
#define multi_tq_new_conf                              frt_multi_tq_new_conf
#define mutex_destroy                                  frt_mutex_destroy
#define mutex_init                                     frt_mutex_init
#define mutex_lock                                     frt_mutex_lock
#define mutex_t                                        frt_mutex_t
#define mutex_trylock                                  frt_mutex_trylock
#define mutex_unlock                                   frt_mutex_unlock
#define non_analyzer_new                               frt_non_analyzer_new
#define non_tokenizer_new                              frt_non_tokenizer_new
#define offset_new                                     frt_offset_new
#define open_cmpd_store                                frt_open_cmpd_store
#define open_cw                                        frt_open_cw
#define open_fs_store                                  frt_open_fs_store
#define open_lock                                      frt_open_lock
#define open_ram_store                                 frt_open_ram_store
#define open_ram_store_and_copy                        frt_open_ram_store_and_copy
#define os_close                                       frt_os_close
#define os_flush                                       frt_os_flush
#define os_new                                         frt_os_new
#define os_pos                                         frt_os_pos
#define os_seek                                        frt_os_seek
#define os_write_byte                                  frt_os_write_byte
#define os_write_bytes                                 frt_os_write_bytes
#define os_write_i32                                   frt_os_write_i32
#define os_write_i64                                   frt_os_write_i64
#define os_write_string                                frt_os_write_string
#define os_write_string_len                            frt_os_write_string_len
#define os_write_u32                                   frt_os_write_u32
#define os_write_u64                                   frt_os_write_u64
#define os_write_vint                                  frt_os_write_vint
#define os_write_vll                                   frt_os_write_vll
#define os_write_voff_t                                frt_os_write_voff_t
#define p_new                                          frt_p_new
#define per_field_analyzer_new                         frt_per_field_analyzer_new
#define pfa_add_field                                  frt_pfa_add_field
#define phq_add_term                                   frt_phq_add_term
#define phq_add_term_abs                               frt_phq_add_term_abs
#define phq_append_multi_term                          frt_phq_append_multi_term
#define phq_new                                        frt_phq_new
#define phq_set_slop                                   frt_phq_set_slop
#define pl_add_occ                                     frt_pl_add_occ
#define pl_cmp                                         frt_pl_cmp
#define pl_new                                         frt_pl_new
#define pq_clear                                       frt_pq_clear
#define pq_clone                                       frt_pq_clone
#define pq_destroy                                     frt_pq_destroy
#define pq_down                                        frt_pq_down
#define pq_free                                        frt_pq_free
#define pq_full                                        frt_pq_full
#define pq_insert                                      frt_pq_insert
#define pq_new                                         frt_pq_new
#define pq_pop                                         frt_pq_pop
#define pq_push                                        frt_pq_push
#define pq_top                                         frt_pq_top
#define prefixq_new                                    frt_prefixq_new
#define print_stacktrace                               frt_print_stacktrace
#define progname                                       frt_progname
#define ptr_eq                                         frt_ptr_eq
#define ptr_hash                                       frt_ptr_hash
#define q_combine                                      frt_q_combine
#define q_create                                       frt_q_create
#define q_create_weight_unsup                          frt_q_create_weight_unsup
#define q_deref                                        frt_q_deref
#define q_destroy_i                                    frt_q_destroy_i
#define q_eq                                           frt_q_eq
#define q_get_query_name                               frt_q_get_query_name
#define q_get_similarity_i                             frt_q_get_similarity_i
#define q_hash                                         frt_q_hash
#define q_new                                          frt_q_new
#define q_weight                                       frt_q_weight
#define qfilt_new                                      frt_qfilt_new
#define qfilt_new_nr                                   frt_qfilt_new_nr
#define qp_add_field                                   frt_qp_add_field
#define qp_clean_str                                   frt_qp_clean_str
#define qp_default_fuzzy_min_sim                       frt_qp_default_fuzzy_min_sim
#define qp_default_fuzzy_pre_len                       frt_qp_default_fuzzy_pre_len
#define qp_destroy                                     frt_qp_destroy
#define qp_new                                         frt_qp_new
#define ram_destroy_buffer                             frt_ram_destroy_buffer
#define ram_new_buffer                                 frt_ram_new_buffer
#define ramo_length                                    frt_ramo_length
#define ramo_reset                                     frt_ramo_reset
#define ramo_write_to                                  frt_ramo_write_to
#define register_for_cleanup                           frt_register_for_cleanup
#define rfilt_new                                      frt_rfilt_new
#define round2                                         frt_round2
#define rq_new                                         frt_rq_new
#define rq_new_less                                    frt_rq_new_less
#define rq_new_more                                    frt_rq_new_more
#define scmp                                           frt_scmp
#define scorer_create                                  frt_scorer_create
#define scorer_destroy_i                               frt_scorer_destroy_i
#define scorer_doc_cmp                                 frt_scorer_doc_cmp
#define scorer_doc_less_than                           frt_scorer_doc_less_than
#define scorer_less_than                               frt_scorer_less_than
#define scorer_new                                     frt_scorer_new
#define searcher_close                                 frt_searcher_close
#define searcher_doc_freq                              frt_searcher_doc_freq
#define searcher_explain                               frt_searcher_explain
#define searcher_explain_w                             frt_searcher_explain_w
#define searcher_get_doc                               frt_searcher_get_doc
#define searcher_get_lazy_doc                          frt_searcher_get_lazy_doc
#define searcher_get_match_vector                      frt_searcher_get_match_vector
#define searcher_get_similarity                        frt_searcher_get_similarity
#define searcher_highlight                             frt_searcher_highlight
#define searcher_max_doc                               frt_searcher_max_doc
#define searcher_rewrite                               frt_searcher_rewrite
#define searcher_search                                frt_searcher_search
#define searcher_search_each                           frt_searcher_search_each
#define searcher_search_fd                             frt_searcher_search_fd
#define setprogname                                    frt_setprogname
#define sfi_close                                      frt_sfi_close
#define sfi_open                                       frt_sfi_open
#define si_advance_norm_gen                            frt_si_advance_norm_gen
#define si_deref                                       frt_si_deref
#define si_has_deletions                               frt_si_has_deletions
#define si_has_separate_norms                          frt_si_has_separate_norms
#define si_new                                         frt_si_new
#define si_uses_compound_file                          frt_si_uses_compound_file
#define sim_coord                                      frt_sim_coord
#define sim_create_default                             frt_sim_create_default
#define sim_decode_norm                                frt_sim_decode_norm
#define sim_destroy                                    frt_sim_destroy
#define sim_encode_norm                                frt_sim_encode_norm
#define sim_idf                                        frt_sim_idf
#define sim_idf_phrase                                 frt_sim_idf_phrase
#define sim_idf_term                                   frt_sim_idf_term
#define sim_length_norm                                frt_sim_length_norm
#define sim_query_norm                                 frt_sim_query_norm
#define sim_sloppy_freq                                frt_sim_sloppy_freq
#define sim_tf                                         frt_sim_tf
#define sis_add_si                                     frt_sis_add_si
#define sis_clear                                      frt_sis_clear
#define sis_curr_seg_file_name                         frt_sis_curr_seg_file_name
#define sis_current_segment_generation                 frt_sis_current_segment_generation
#define sis_del_at                                     frt_sis_del_at
#define sis_del_from_to                                frt_sis_del_from_to
#define sis_destroy                                    frt_sis_destroy
#define sis_new                                        frt_sis_new
#define sis_new_segment                                frt_sis_new_segment
#define sis_put                                        frt_sis_put
#define sis_read                                       frt_sis_read
#define sis_read_current_version                       frt_sis_read_current_version
#define sis_write                                      frt_sis_write
#define sort_add_sort_field                            frt_sort_add_sort_field
#define sort_clear                                     frt_sort_clear
#define sort_destroy                                   frt_sort_destroy
#define sort_field_auto_new                            frt_sort_field_auto_new
#define sort_field_byte_new                            frt_sort_field_byte_new
#define sort_field_destroy                             frt_sort_field_destroy
#define sort_field_doc_new                             frt_sort_field_doc_new
#define sort_field_float_new                           frt_sort_field_float_new
#define sort_field_int_new                             frt_sort_field_int_new
#define sort_field_new                                 frt_sort_field_new
#define sort_field_score_new                           frt_sort_field_score_new
#define sort_field_string_new                          frt_sort_field_string_new
#define sort_field_to_s                                frt_sort_field_to_s
#define sort_new                                       frt_sort_new
#define sort_to_s                                      frt_sort_to_s
#define spanfq_new                                     frt_spanfq_new
#define spanfq_new_nr                                  frt_spanfq_new_nr
#define spanmtq_add_term                               frt_spanmtq_add_term
#define spanmtq_new                                    frt_spanmtq_new
#define spanmtq_new_conf                               frt_spanmtq_new_conf
#define spannq_add_clause                              frt_spannq_add_clause
#define spannq_add_clause_nr                           frt_spannq_add_clause_nr
#define spannq_new                                     frt_spannq_new
#define spanoq_add_clause                              frt_spanoq_add_clause
#define spanoq_add_clause_nr                           frt_spanoq_add_clause_nr
#define spanoq_new                                     frt_spanoq_new
#define spanprq_new                                    frt_spanprq_new
#define spantq_new                                     frt_spantq_new
#define spanxq_new                                     frt_spanxq_new
#define spanxq_new_nr                                  frt_spanxq_new_nr
#define standard_analyzer_new                          frt_standard_analyzer_new
#define standard_analyzer_new_with_words               frt_standard_analyzer_new_with_words
#define standard_analyzer_new_with_words_len           frt_standard_analyzer_new_with_words_len
#define standard_tokenizer_new                         frt_standard_tokenizer_new
#define std_scan                                       frt_std_scan
#define std_scan_mb                                    frt_std_scan_mb
#define std_scan_utf8                                  frt_std_scan_utf8
#define stde_new                                       frt_stde_new
#define ste_clone                                      frt_ste_clone
#define ste_close                                      frt_ste_close
#define ste_new                                        frt_ste_new
#define stem_filter_new                                frt_stem_filter_new
#define stop_filter_new                                frt_stop_filter_new
#define stop_filter_new_with_words                     frt_stop_filter_new_with_words
#define stop_filter_new_with_words_len                 frt_stop_filter_new_with_words_len
#define store_deref                                    frt_store_deref
#define store_destroy                                  frt_store_destroy
#define store_new                                      frt_store_new
#define store_to_s                                     frt_store_to_s
#define stpe_new                                       frt_stpe_new
#define str_hash                                       frt_str_hash
#define strapp                                         frt_strapp
#define strfmt                                         frt_strfmt
#define strsort                                        frt_strsort
#define sym_hash                                       frt_sym_hash

#endif
