#ifndef FRT_INTERNAL_H
#define FRT_INTERNAL_H

/* Functions */
#define filt_eq                                        frt_filt_eq
#define filt_get_bv                                    frt_filt_get_bv
#define filt_hash                                      frt_filt_hash
#define filter_clone_size                              frt_filter_clone_size
#define filter_ft                                      frt_filter_ft
#define fis_add_field                                  frt_fis_add_field
#define fis_by_number                                  frt_fis_by_number
#define fis_deref                                      frt_fis_deref
#define fis_get_field                                  frt_fis_get_field
#define fis_get_field_num                              frt_fis_get_field_num
#define fis_get_or_add_field                           frt_fis_get_or_add_field
#define fis_new                                        frt_fis_new
#define fis_read                                       frt_fis_read
#define fis_to_s                                       frt_fis_to_s
#define fis_write                                      frt_fis_write
#define float2byte                                     frt_float2byte
#define float2int                                      frt_float2int
#define fn_for_generation                              frt_fn_for_generation
#define fq_new                                         frt_fq_new
#define fr_clone                                       frt_fr_clone
#define fr_close                                       frt_fr_close
#define fr_get_doc                                     frt_fr_get_doc
#define fr_get_field_tv                                frt_fr_get_field_tv
#define fr_get_lazy_doc                                frt_fr_get_lazy_doc
#define fr_get_tv                                      frt_fr_get_tv
#define fr_open                                        frt_fr_open
#define free_ft                                        frt_free_ft
#define fshq_pq_destroy                                frt_fshq_pq_destroy
#define fshq_pq_down                                   frt_fshq_pq_down
#define fshq_pq_insert                                 frt_fshq_pq_insert
#define fshq_pq_new                                    frt_fshq_pq_new
#define fshq_pq_pop                                    frt_fshq_pq_pop
#define fshq_pq_pop_fd                                 frt_fshq_pq_pop_fd
#define fuzq_new                                       frt_fuzq_new
#define fuzq_new_conf                                  frt_fuzq_new_conf
#define fuzq_score                                     frt_fuzq_score
#define fw_add_doc                                     frt_fw_add_doc
#define fw_add_postings                                frt_fw_add_postings
#define fw_close                                       frt_fw_close
#define fw_open                                        frt_fw_open
#define fw_write_tv_index                              frt_fw_write_tv_index
#define get_float_value                                frt_get_float_value
#define get_integer_value                              frt_get_integer_value
#define get_stacktrace                                 frt_get_stacktrace
#define get_string_value                               frt_get_string_value
#define h_clear                                        frt_h_clear
#define h_clone                                        frt_h_clone
#define h_clone_ft                                     frt_h_clone_ft
#define h_del                                          frt_h_del
#define h_del_int                                      frt_h_del_int
#define h_destroy                                      frt_h_destroy
#define h_each                                         frt_h_each
#define h_each_key_val_ft                              frt_h_each_key_val_ft
#define h_get                                          frt_h_get
#define h_get_int                                      frt_h_get_int
#define h_has_key                                      frt_h_has_key
#define h_has_key_int                                  frt_h_has_key_int
#define h_lookup                                       frt_h_lookup
#define h_lookup_ft                                    frt_h_lookup_ft
#define h_new                                          frt_h_new
#define h_new_int                                      frt_h_new_int
#define h_new_ptr                                      frt_h_new_ptr
#define h_new_str                                      frt_h_new_str
#define h_rem                                          frt_h_rem
#define h_rem_int                                      frt_h_rem_int
#define h_set                                          frt_h_set
#define h_set_ext                                      frt_h_set_ext
#define h_set_int                                      frt_h_set_int
#define h_set_safe                                     frt_h_set_safe
#define h_set_safe_int                                 frt_h_set_safe_int
#define h_str_print_keys                               frt_h_str_print_keys
#define hash_finalize                                  frt_hash_finalize
#define hash_ft                                        frt_hash_ft
#define hlp_string_diff                                frt_hlp_string_diff
#define hs_add                                         frt_hs_add
#define hs_add_safe                                    frt_hs_add_safe
#define hs_clear                                       frt_hs_clear
#define hs_del                                         frt_hs_del
#define hs_destroy                                     frt_hs_destroy
#define hs_exists                                      frt_hs_exists
#define hs_free                                        frt_hs_free
#define hs_merge                                       frt_hs_merge
#define hs_new                                         frt_hs_new
#define hs_new_ptr                                     frt_hs_new_ptr
#define hs_new_str                                     frt_hs_new_str
#define hs_orig                                        frt_hs_orig
#define hs_rem                                         frt_hs_rem
#define hyphen_filter_new                              frt_hyphen_filter_new
#define i16                                            frt_i16
#define i32                                            frt_i32
#define i64                                            frt_i64
#define icmp                                           frt_icmp
#define icmp_risky                                     frt_icmp_risky
#define imalloc                                        frt_imalloc
#define index_add_array                                frt_index_add_array
#define index_add_doc                                  frt_index_add_doc
#define index_add_string                               frt_index_add_string
#define index_auto_flush_ir                            frt_index_auto_flush_ir
#define index_auto_flush_iw                            frt_index_auto_flush_iw
#define index_create                                   frt_index_create
#define index_delete                                   frt_index_delete
#define index_delete_id                                frt_index_delete_id
#define index_delete_query                             frt_index_delete_query
#define index_delete_query_str                         frt_index_delete_query_str
#define index_delete_term                              frt_index_delete_term
#define index_destroy                                  frt_index_destroy
#define index_explain                                  frt_index_explain
#define index_flush                                    frt_index_flush
#define index_get_doc                                  frt_index_get_doc
#define index_get_doc_id                               frt_index_get_doc_id
#define index_get_doc_term                             frt_index_get_doc_term
#define index_get_doc_ts                               frt_index_get_doc_ts
#define index_get_query                                frt_index_get_query
#define index_has_del                                  frt_index_has_del
#define index_is_deleted                               frt_index_is_deleted
#define index_is_locked                                frt_index_is_locked
#define index_new                                      frt_index_new
#define index_optimize                                 frt_index_optimize
#define index_search_str                               frt_index_search_str
#define index_size                                     frt_index_size
#define index_term_id                                  frt_index_term_id
#define init                                           frt_init
#define int2float                                      frt_int2float
#define ir_add_cache                                   frt_ir_add_cache
#define ir_close                                       frt_ir_close
#define ir_commit                                      frt_ir_commit
#define ir_create                                      frt_ir_create
#define ir_delete_doc                                  frt_ir_delete_doc
#define ir_destroy                                     frt_ir_destroy
#define ir_doc_freq                                    frt_ir_doc_freq
#define ir_get_doc_with_term                           frt_ir_get_doc_with_term
#define ir_get_field_num                               frt_ir_get_field_num
#define ir_get_norms                                   frt_ir_get_norms
#define ir_get_norms_i                                 frt_ir_get_norms_i
#define ir_get_norms_into                              frt_ir_get_norms_into
#define ir_index_exists                                frt_ir_index_exists
#define ir_is_latest                                   frt_ir_is_latest
#define ir_open                                        frt_ir_open
#define ir_set_norm                                    frt_ir_set_norm
#define ir_term_positions_for                          frt_ir_term_positions_for
#define ir_terms                                       frt_ir_terms
#define ir_terms_from                                  frt_ir_terms_from
#define ir_undelete_all                                frt_ir_undelete_all
#define is2os_copy_bytes                               frt_is2os_copy_bytes
#define is2os_copy_vints                               frt_is2os_copy_vints
#define is_clone                                       frt_is_clone
#define is_close                                       frt_is_close
#define is_new                                         frt_is_new
#define is_pos                                         frt_is_pos
#define is_read_byte                                   frt_is_read_byte
#define is_read_bytes                                  frt_is_read_bytes
#define is_read_i32                                    frt_is_read_i32
#define is_read_i64                                    frt_is_read_i64
#define is_read_string                                 frt_is_read_string
#define is_read_string_safe                            frt_is_read_string_safe
#define is_read_u32                                    frt_is_read_u32
#define is_read_u64                                    frt_is_read_u64
#define is_read_vint                                   frt_is_read_vint
#define is_read_vll                                    frt_is_read_vll
#define is_read_voff_t                                 frt_is_read_voff_t
#define is_seek                                        frt_is_seek
#define is_skip_vints                                  frt_is_skip_vints
#define isea_doc_freq                                  frt_isea_doc_freq
#define isea_new                                       frt_isea_new
#define iw_add_doc                                     frt_iw_add_doc
#define iw_add_readers                                 frt_iw_add_readers
#define iw_close                                       frt_iw_close
#define iw_commit                                      frt_iw_commit
#define iw_delete_term                                 frt_iw_delete_term
#define iw_delete_terms                                frt_iw_delete_terms
#define iw_doc_count                                   frt_iw_doc_count
#define iw_open                                        frt_iw_open
#define iw_optimize                                    frt_iw_optimize
#define lazy_df_get_bytes                              frt_lazy_df_get_bytes
#define lazy_df_get_data                               frt_lazy_df_get_data
#define lazy_doc_close                                 frt_lazy_doc_close
#define lazy_doc_get                                   frt_lazy_doc_get
#define legacy_standard_analyzer_new                   frt_legacy_standard_analyzer_new
#define legacy_standard_analyzer_new_with_words        frt_legacy_standard_analyzer_new_with_words
#define legacy_standard_analyzer_new_with_words_len    frt_legacy_standard_analyzer_new_with_words_len
#define legacy_standard_tokenizer_new                  frt_legacy_standard_tokenizer_new
#define letter_analyzer_new                            frt_letter_analyzer_new
#define letter_tokenizer_new                           frt_letter_tokenizer_new
#define lmalloc                                        frt_lmalloc
#define lowercase_filter_new                           frt_lowercase_filter_new
#define lt_ft                                          frt_lt_ft

#endif
