/* Generated by Snowball 2.2.0 - https://snowballstem.org/ */

extern struct SN_env * romanian_ISO_8859_2_create_env(void);
extern void romanian_ISO_8859_2_close_env(struct SN_env * z);

extern int romanian_ISO_8859_2_stem(struct SN_env * z);
