/* Generated by Snowball 2.2.0 - https://snowballstem.org/ */

extern struct SN_env * finnish_ISO_8859_1_create_env(void);
extern void finnish_ISO_8859_1_close_env(struct SN_env * z);

extern int finnish_ISO_8859_1_stem(struct SN_env * z);
