/* Generated by Snowball 2.2.0 - https://snowballstem.org/ */

extern struct SN_env * russian_KOI8_R_create_env(void);
extern void russian_KOI8_R_close_env(struct SN_env * z);

extern int russian_KOI8_R_stem(struct SN_env * z);
